# Generated by Django 5.2.5 on 2026-04-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('exam_name', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=50)),
                ('marks', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='results/')),
                ('year', models.IntegerField()),
            ],
        ),
    ]
