# Generated by Django 5.2.5 on 2026-04-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_studentresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='student_name',
            new_name='name',
        ),
    ]
