# Generated by Django 5.2.5 on 2026-04-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_company_hero_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='button_text',
            field=models.CharField(default='Get Started', max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
