# Generated by Django 5.2.5 on 2026-04-24 06:39

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_company_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('father_name_or_husband_name', models.CharField(max_length=255)),
                ('father_or_husband_occupation', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('guardian_phone_no', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number with 10 to 15 digits.', regex='^\\+?[0-9]{10,15}$')])),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField()),
                ('student_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('category', models.CharField(choices=[('GEN', 'GEN'), ('ST', 'ST'), ('SC', 'SC'), ('OBC', 'OBC')], max_length=3)),
                ('tenth_board_name', models.CharField(max_length=255)),
                ('tenth_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenth_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('twelfth_board_name', models.CharField(max_length=255)),
                ('twelfth_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twelfth_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('university_name', models.CharField(max_length=255)),
                ('university_cgpa_or_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('university_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('photo', models.ImageField(upload_to=main.models.student_photo_upload_path, validators=[django.core.validators.validate_image_file_extension])),
                ('adhar_card_no', models.CharField(db_index=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Adhar card number must be exactly 12 digits.', regex='^[0-9]{12}$')])),
                ('ssmid_no', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='SSMID number must contain 8 to 20 digits.', regex='^[0-9]{8,20}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['student_no'], name='main_studen_student_e73ecd_idx'), models.Index(fields=['adhar_card_no'], name='main_studen_adhar_c_962756_idx'), models.Index(fields=['ssmid_no'], name='main_studen_ssmid_n_145680_idx')],
            },
        ),
    ]
