# Generated by Django 5.2.5 on 2026-05-16 09:08

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='company/', validators=[django.core.validators.validate_image_file_extension, main.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', validators=[django.core.validators.validate_image_file_extension, main.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/', validators=[django.core.validators.validate_image_file_extension, main.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', validators=[django.core.validators.validate_image_file_extension, main.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images/', validators=[django.core.validators.validate_image_file_extension, main.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to=main.models.student_photo_upload_path, validators=[django.core.validators.validate_image_file_extension, main.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='photo',
            field=models.ImageField(upload_to='results/', validators=[django.core.validators.validate_image_file_extension, main.models.validate_image_size]),
        ),
    ]
